"""Catalog builder script.

Reads `image_manifest.json` generated by the image acquisition step, creates up to
`MAX_PRODUCTS` Product rows, populates minimal required fields, and links a
`ProductImage` record pointing at the downloaded image.

The script can be executed directly (`python -m app.ai.catalog_builder`) or
imported and called from other tooling.
"""

import json
import os
import uuid
from pathlib import Path
from typing import List, Dict

from sqlalchemy.exc import IntegrityError

# Project imports
from ..db import SessionLocal
from ..models import Product, ProductImage

# Configuration --------------------------------------------------------------
MAX_PRODUCTS = int(os.getenv("CATALOG_MAX_PRODUCTS", "500"))
MANIFEST_PATH = Path(os.getenv("IMAGE_MANIFEST_PATH", "backend/exports/image_manifest.json"))
AUDIT_LOG_PATH = Path(os.getenv("CATALOG_AUDIT_LOG", "backend/exports/catalog_audit.log"))


def load_manifest() -> List[Dict]:
    """Load the image manifest generated by `acquire_fashion_images.py`."""
    if not MANIFEST_PATH.is_file():
        raise FileNotFoundError(f"Manifest not found at {MANIFEST_PATH}")
    with MANIFEST_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data


def create_product(session, entry: Dict) -> Product:
    """Create a `Product` instance from a manifest entry.

    Only the fields required for later pipeline steps are populated. Missing
    optional data is filled with sensible defaults.
    """
    product = Product(
        id=str(uuid.uuid4()),
        name=entry.get("title", "Untitled"),
        description=entry.get("description", ""),
        category=entry.get("category", "Uncategorized"),
        brand=entry.get("brand", "Generic"),
        price=entry.get("price", 0.0),
        image_url=entry.get("download_url"),
        source="placeholder",
        source_page=entry.get("source_page"),
        license_attribution=entry.get("license"),
        author=entry.get("author"),
        image_embedding_status="pending",
        text_embedding_status="pending",
    )
    session.add(product)
    session.flush()
    if product.image_url:
        img = ProductImage(
            product_id=product.id,
            url=product.image_url,
            alt_text=product.name,
            sort_order=0,
        )
        session.add(img)
    return product


def run_audit(session) -> List[str]:
    """Simple quality audit – returns a list of warning strings."""
    warnings = []
    for prod in session.query(Product).all():
        if prod.image_embedding_vector is None and prod.image_embedding_status != "pending":
            warnings.append(f"Product {prod.id} missing image embedding vector.")
        if prod.text_embedding_vector is None and prod.text_embedding_status != "pending":
            warnings.append(f"Product {prod.id} missing text embedding vector.")
        required = [prod.name, prod.category, prod.brand]
        if any(r is None or r == "" for r in required):
            warnings.append(f"Product {prod.id} has empty required fields.")
    return warnings


def main():
    manifest = load_manifest()
    manifest = manifest[:MAX_PRODUCTS]
    session = SessionLocal()
    created = 0
    try:
        for entry in manifest:
            create_product(session, entry)
            created += 1
        session.commit()
        audit_warnings = run_audit(session)
        with AUDIT_LOG_PATH.open("w", encoding="utf-8") as log:
            log.write(f"Created {created} products.\n")
            if audit_warnings:
                log.write("\nQuality audit warnings:\n")
                for w in audit_warnings:
                    log.write(f"- {w}\n")
            else:
                log.write("\nNo audit warnings – catalog looks healthy.\n")
        print(f"Catalog seed completed. Audit written to {AUDIT_LOG_PATH}")
    except IntegrityError as e:
        session.rollback()
        print(f"Database integrity error: {e}")
    finally:
        session.close()

if __name__ == "__main__":
    main()
