// File generated by FlutterFire CLI & configured with project trenzy2400 credentials.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRiWHWzGTDCEfmZ8m8h927jnnU4eTAeM',
    appId: '1:262146737740:web:19aa430ab6eebe26b6d6e9',
    messagingSenderId: '262146737740',
    projectId: 'trenzy2400',
    authDomain: 'trenzy2400.firebaseapp.com',
    storageBucket: 'trenzy2400.firebasestorage.app',
    measurementId: 'G-0EWF8FCQV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_owu_-gg4KGVjo11Lq8pGUSHj5xFQ_YI',
    appId: '1:262146737740:android:187c3407ac2ef8a8b6d6e9',
    messagingSenderId: '262146737740',
    projectId: 'trenzy2400',
    storageBucket: 'trenzy2400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_8bM43Ln5ZSZe6DefCQlUyPMv5iQs4s',
    appId: '1:262146737740:ios:b1fe623c4137ffc6b6d6e9',
    messagingSenderId: '262146737740',
    projectId: 'trenzy2400',
    storageBucket: 'trenzy2400.firebasestorage.app',
    iosClientId:
        '262146737740-4m8me74kb83qmdia70aujo5bs1af0lr3.apps.googleusercontent.com',
    iosBundleId: 'com.trenzy.trenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_8bM43Ln5ZSZe6DefCQlUyPMv5iQs4s',
    appId: '1:262146737740:ios:b1fe623c4137ffc6b6d6e9',
    messagingSenderId: '262146737740',
    projectId: 'trenzy2400',
    storageBucket: 'trenzy2400.firebasestorage.app',
    iosClientId:
        '262146737740-4m8me74kb83qmdia70aujo5bs1af0lr3.apps.googleusercontent.com',
    iosBundleId: 'com.trenzy.trenzy',
  );
}
